### PR TITLE
Fix typescript error

### PR DESCRIPTION
**Pull request by Kreijstal**
If not globalThis then Window, otherwise nothing, I slopily did another check and that was a bug, this should fix it.
Fixes bug introduced by #636

### CODE REVIEW

**Comment by Kreijstal** [comment]
Looking at the error:

yarn run v1.22.22
$ tsc --noEmit
Error: packages/react/src/components/FormatSearch/index.tsx(51,68): error TS2339: Property 'pos' does not exist on type '{ name: string; pos: string; value: string; } | { name: string; pos: string; value: string; } | { name: string; value: string; }'.
  Property 'pos' does not exist on type '{ name: string; value: string; }'.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 2.

It seems it is an unrelated error.
